const types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_AUTH: 'GET_AUTH',
};

export default types;
